### PR TITLE
Travis take (3)

### PR DESCRIPTION
**Pull request by lupyana**
Trial number 3.

See #31

### CODE REVIEW

**Comment by lupyana** [comment]
- I have attended the previous comment and changed the file based on your recommendation,

- My theory to why it is not working is that, there is not package.json file on the root folder. That is why the script is executed and fails, however packaje.json is present on the backend and frontend folders.

**Comment by lupyana** [comment]
I attempted moving the travis.yml file to the backend folder however when I pushed and filed a pr it was not picked up. So I think that it is essential to place the travis file on root directory

**Comment by BenMaruchu** [comment]
So travis runs but do you have `yarn test` configured? @lupyana

**Comment by lupyana** [comment]
> So travis runs but do you have `yarn test` configured? @lupyana

In the backend folder, there are tests that I have configured. Runing them localy they pass

**Comment by BenMaruchu** [comment]
@lupyana I have checked travis error is `error Couldn't find a package.json file in "/home/travis/build/lupyana/Ride-My-Way"` so It is supposed to be at root folder as you said

**Comment by lupyana** [comment]
> @lupyana I have checked travis error is `error Couldn't find a package.json file in "/home/travis/build/lupyana/Ride-My-Way"` so It is supposed to be at root folder as you said

I thought so too, as i said on the previous comment
_Originally posted by @lupyana in https://github.com/lupyana/Ride-My-Way/pull/38#issuecomment-495641669_

May i ask, how did you get that error message?

**Comment by BenMaruchu** [comment]
@lupyana you can always go direct to travis site and see the error. so click checks tab and click The build link it wil navigate you to travis

**Pull request closed without merging**
