### PR TITLE
Challenge 4

### PR DESCRIPTION
**Pull request by lupyana**
This pr includes the following features:

- User registration #53 
- User Verification #54 
- User Login #55 
- Fetch all available offers #32 
- Fetch details of a specific offer #45 
- Make a request to join a ride. #43 
- Create a ride offer #44 
- Fetch all ride requests 
- Accept or reject a ride request. #58 
- Added JWT support to the app

### CODE REVIEW

**Comment by BenMaruchu** [comment]
@lupyana which nodejs version are you using?

**Comment by lupyana** [comment]
version 8

**Comment by lupyana** [comment]
> @lupyana which nodejs version are you using?

v8.15.1 to be more specific

**Comment by BenMaruchu** [comment]
ok for that node version esmodule was still experimental but I think for node 12 it is supported already

**Review by BenMaruchu — APPROVED** [review]

**Pull request merged**
