### PR TITLE
Feat/join a ride

### PR DESCRIPTION
**Pull request by lupyana**
- Create api end point and test case for joining a ride see #43 
- Added coveralls to project #47
- Updated readme file

### CODE REVIEW

**Review by BenMaruchu — COMMENTED** [review]
@lupyana Coverage files ain't them generated on running tests?

**Comment by lupyana** [comment]
> @lupyana Coverage files ain't them generated on running tests?

If you mean the coverage folder, it is auto generated after running tests

**Comment by BenMaruchu** [comment]
So what happens if tests are executed in travis?

**Comment by lupyana** [comment]
> So what happens if tests are executed in travis?

Travis will build and perform the unit and coverage tests, After is is complete coverals will read the repo, to get results of the coverage test.It will prepare a report showing which parts of the code wasn’t covered by the test suites

**Review by makoscafee — CHANGES_REQUESTED** [review]
All LGTM just one minor thing is coverage folder should not be committed, It is unnecessary. [See](https://help.github.com/articles/ignoring-files/).  or you can see sample node .gitignore from [here](https://www.gitignore.io/api/node)

**Comment by BenMaruchu** [comment]
ok @lupyana  but I agree with @makoscafee from what I know coverage files are not committed in repos. I think @makoscafee have explained it well there

**Comment by lupyana** [comment]
> ok @lupyana but I agree with @makoscafee from what I know coverage files are not committed in repos. I think @makoscafee have explained it well there

Yes noted, however it is already in my gitignore file. I have to find anotherway to remove it from the remote repo

**Comment by lupyana** [comment]
> All LGTM just one minor thing is coverage folder should not be committed, It is unnecessary. [See](https://help.github.com/articles/ignoring-files/). or you can see sample node .gitignore from [here](https://www.gitignore.io/api/node)

@makoscafee  I have removed the coverage folder

**Review by makoscafee — APPROVED** [review]

**Comment by makoscafee** [comment]
LGTM you can merge.

**Pull request merged**
